### ISSUE TITLE
1.12.2 a few mistakes

### ISSUE THREAD

**Issue by TeQTabanca** [ScalerGames/BroadcastPlus#1]
### Every 5 minutes i get this error
> [12:47:27 WARN]: [BroadcastPlus] Task #54 for BroadcastPlus v2.7.0 generated an exception
> java.lang.IllegalArgumentException: bound must be positive
> at java.util.Random.nextInt(Random.java:388) ~[?:?]
> at Dev.ScalerGames.BroadcastPlus.Methods.AutoBroadcast$1.run(`AutoBroadcast`.java:25) ~[BroadcastPlus-2.7.0.jar:?]
> at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-79a30d7-acbc348]
> at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-79a30d7-acbc348]
> at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-79a30d7-acbc348]
> at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
> at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
> at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
> at java.lang.Thread.run(Thread.java:829) [?:?]

### I saw the autobroadcast text in the error, but I turned it off from the settings.
![autobroadcast config](https://user-images.githubusercontent.com/89253304/149934370-9f50db17-11ad-442c-9096-e2c5b44bb963.png)

### Unable to disable autobroadcast
![autobroadcast config 2](https://user-images.githubusercontent.com/89253304/149936526-ae0a776f-98c7-41f3-a91f-cbebe2476fd3.png)
![presets config](https://user-images.githubusercontent.com/89253304/149936590-0e5afcc1-0632-45e6-bd11-419efa3c9313.png)
![open despite being closed](https://user-images.githubusercontent.com/89253304/149936550-aee1d84f-99ac-4fc1-bfc6-807a60940311.png)

### If I type the word that is not in the gui.yml file, I get this error.

> [12:55:05 INFO]: TeqTabanca issued server command: /broadcast gui Test
> [12:55:05 ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'broadcast' in plugin BroadcastPlus v2.7.0
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-acbc348]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
>         at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
>         at java.lang.Thread.run(Thread.java:829) [?:?]
> Caused by: java.lang.NullPointerException
>         at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:44) ~[PlaceholderAPI-2.10.10.jar:?]
>         at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[PlaceholderAPI-2.10.10.jar:?]
>         at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[PlaceholderAPI-2.10.10.jar:?]
>         at Dev.ScalerGames.BroadcastPlus.Utils.Format.placeholder(Format.java:31) ~[BroadcastPlus-2.7.0.jar:?]
>         at Dev.ScalerGames.BroadcastPlus.Methods.Gui.GuiCreator.generate(GuiCreator.java:17) ~[BroadcastPlus-2.7.0.jar:?]
>         at Dev.ScalerGames.BroadcastPlus.Commands.Broadcasting.Broadcast.onCommand(Broadcast.java:79) ~[BroadcastPlus-2.7.0.jar:?]
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         ... 15 more

### Bossbar message not working
![bossbar config](https://user-images.githubusercontent.com/89253304/149936857-982bd3b9-96e2-41f1-ad6a-d3d540367009.png)
![invalid timing](https://user-images.githubusercontent.com/89253304/149936812-842fb7c6-4c8e-445e-a035-0407c8ea3f6b.png)

### NOTE:
**I use translation because my English is bad, I hope you understand.**

**Comment by ScalerGames** [comment]
Hi I will fix some of the issues that you have pointed out. For the boss bar you need to add the color, style, time and so on in the command it's self. There should be tab completers which do provide options for you. Did you restart the server after disabling auto broadcast?

**Comment by TeQTabanca** [comment]
### If I just type /broadcast chat I get an error

> [20:40:53 INFO]: TeqTabanca issued server command: /broadcast chat
> [20:40:53 ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'broadcast' in plugin BroadcastPlus v2.7.0
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-acbc348]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
>         at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
>         at java.lang.Thread.run(Thread.java:829) [?:?]
> Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
>         at Dev.ScalerGames.BroadcastPlus.Commands.Broadcasting.Broadcast.onCommand(Broadcast.java:38) ~[BroadcastPlus-2.7.0.jar:?]
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         ... 15 more

### If I just type /broadcast title I get an error

> [20:41:09 INFO]: TeqTabanca issued server command: /broadcast title
> [20:41:09 ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'broadcast' in plugin BroadcastPlus v2.7.0
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-acbc348]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
>         at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
>         at java.lang.Thread.run(Thread.java:829) [?:?]
> Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
>         at Dev.ScalerGames.BroadcastPlus.Commands.Broadcasting.Broadcast.onCommand(Broadcast.java:66) ~[BroadcastPlus-2.7.0.jar:?]
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-79a30d7-acbc348]
>         ... 15 more

### /broadcastworld chat No error

### /broadcastworld title No error

### /groupbroadcast chat No error

### /groupbroadcast title No error

### /localbroadcast chat No error

### /localbroadcast title No error

**Comment by ScalerGames** [comment]
These errors should now be fixed in the latest update. The auto broadcast is now disabled by default and can be enabled via the config. If enabled it does need messages to broadcast so it can function. All the /broadcast [method] should be fixed as well as the invalid gui error.
